// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udpRequest.proto

package com.roomreservation.protobuf.protos;

public final class UdpResquestProtos {
  private UdpResquestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_roomreservation_collection_udpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_roomreservation_collection_udpRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020udpRequest.proto\022\036com.roomreservation." +
      "collection\"w\n\nudpRequest\022\016\n\006action\030\001 \002(\t" +
      "\022\021\n\tbookingId\030\002 \001(\005\022\014\n\004date\030\003 \001(\t\022\022\n\ncam" +
      "pusName\030\004 \001(\t\022\022\n\nroomNumber\030\005 \001(\005\022\020\n\010tim" +
      "eslot\030\006 \001(\tB:\n#com.roomreservation.proto" +
      "buf.protosB\021UdpResquestProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_roomreservation_collection_udpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_roomreservation_collection_udpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_roomreservation_collection_udpRequest_descriptor,
        new java.lang.String[] { "Action", "BookingId", "Date", "CampusName", "RoomNumber", "Timeslot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
