// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udpResponse.proto

package com.roomreservation.protobuf.protos;

public final class UdpResponseProtos {
  private UdpResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_roomreservation_collection_udpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_roomreservation_collection_udpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021udpResponse.proto\022\036com.roomreservation" +
      ".collection\"q\n\013udpResponse\022\020\n\010response\030\001" +
      " \002(\t\022\020\n\010dateTime\030\002 \002(\t\022\023\n\013requestType\030\003 " +
      "\002(\t\022\031\n\021requestParameters\030\004 \002(\t\022\016\n\006status" +
      "\030\005 \002(\010B:\n#com.roomreservation.protobuf.p" +
      "rotosB\021UdpResponseProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_roomreservation_collection_udpResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_roomreservation_collection_udpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_roomreservation_collection_udpResponse_descriptor,
        new java.lang.String[] { "Response", "DateTime", "RequestType", "RequestParameters", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
